name: Codebase Analyzer Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .  # Install the package itself
        pip install pytest pytest-cov pytest-mock pytest-benchmark radon lizard

    - name: Run tests with coverage
      run: |
        pytest tests/ -v --cov=codebase_analyzer --cov-report=xml

    - name: Upload coverage report
      uses: codecov/codecov-action@v3
      with:
        files: ./coverage.xml
        token: ${{ secrets.CODECOV_TOKEN }}  # Set this in GitHub secrets if private repo